### ISSUE TITLE
Cannot configure filters in visual editor

### ISSUE THREAD

**Issue by tboyce021** [thomasloven/lovelace-auto-entities#282]
I'm getting the following error when trying to select the "property" to filter on through the visual editor:
```
auto-entities.js?hacstag=1677445841110:1 Uncaught TypeError: Cannot assign to read only property 'filter' of object '#<Object>'
    at Pt._changeFilter (auto-entities.js?hacstag=1677445841110:1:30990)
    at Pt.<anonymous> (auto-entities.js?hacstag=1677445841110:69:46)
    at q.handleEvent (auto-entities.js?hacstag=1677445841110:1:14334)
    at i (typography.js:181:1)
    at ShadowRoot.<anonymous> (ha-form.ts:33:1)
    at i (typography.js:181:1)
    at F.value (ha-form-select.ts:15:1)
    at F.handleEvent (styles.ts:368:1)
    at i (typography.js:181:1)
    at F.value (ha-selector-select.ts:19:1)
```
If I manually add a filter, e.g. `domain: light`, through the code editor then switch back to the visual editor then it appears correctly. However, trying to add another filter or change the current one still results in the same error. I've tried clearing cache, restarting HA, etc. but no luck so far.

**Comment by r100gs** [comment]
Hello, If I try to set filters via ui my homeassistant dashboard freezes. I have been waiting arround half an hour but nothing happend. Closing the tab and reopening is the only way to get it working again.

Best regards,
Stefan

**Comment by timnolte** [comment]
I have also been experiencing the same issue. This add-on appears to be broken now with the visual editor.

**Comment by techander** [comment]
Same for me. Can't add any property using the visual editor any more. If I choose a property, then there will not show a value field and nothing is added to the yaml-code. Only manual through yaml is working. Will there soon be a fix for this? Love the card, but miss a working visual editor.

**Comment by hundehausen** [comment]
I still have this problem

**Comment by JonasJoKuJonas** [comment]
I got 2 instances of ha. On the raspberry pi every thing is working fine but on the ha that is running in docker it will not work with chrome, edge or firefox

**Comment by Shocktrooper** [comment]
I also have this issue
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/2646851/b2276bab-0c81-4445-b36d-ede3b004fb80)

**Comment by Misiu** [comment]
I got this error while trying to add another property to filters:
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/1741838/c9dcf482-6465-471a-9e02-77041fa88411)

**Comment by iamandymcinnes** [comment]
I've got this as well, it's like it's trying to refresh to render what your selection is, but you haven't had chance to set a value for the property. A little unusable atm sadly as it's a really useful component.

**Comment by nicolinuxfr** [comment]
Same problem here, I guess I will use the YAML then…
