### ISSUE TITLE
Cannot add new filtering properties on old cards

### ISSUE THREAD

**Issue by wsw70** [thomasloven/lovelace-auto-entities#483]
I created a card about 2 or 3 years ago. It is systematically updated to the latest version (currently 1.13.0).

After embracing Labels, I wanted to add a label-based filter to a card. This is how it looks like when opening the editor.

![image](https://github.com/user-attachments/assets/688c19e3-08a3-43ea-b49b-f39afa942eb4)

When trying to select "Label" from the "Select property" dropdown, I can select it but after a few seconds it vanishes. This is a screenshot quickly snagged when "Label" was still visible:

![image](https://github.com/user-attachments/assets/91f0419a-e4c2-430b-bd55-736deac7723e)

There is no entry for the label.

- I can add the filer via the YAML and it then shows up in the editor
- the issue is true for any property - I just ended up discovering it when trying to add a Label

**Comment by ccle610** [comment]
Also, properties can't be changed anymore. It goes back to the original value after a short time, surprising . .  . 
Not shure, if the Card will show the Infos, if the property will be true (i.e. Battery below 10%)

**Comment by wsw70** [comment]
> Also, properties can't be changed anymore. It goes back to the original value after a short time, surprising . . . Not shure, if the Card will show the Infos, if the property will be true (i.e. Battery below 10%)

Right. You can still change them in the YAML but the visual editor has a problem.

**Comment by ccle610** [comment]
But that is only half the truth. 
As soon as I exit the YAML editor after saving and call up the card once again, it is the old value again. . . runnung in cyrcles.

**Comment by Calzor-Suzay** [comment]
I'm new to Auto entities and I have this exact same problem [link from HA forum](https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801/1574?u=calzor_suzay)

The dropdown entries 'vanish'.
Tried with Edge and Chrome.

**Comment by Mariusthvdb** [comment]
is this only happening with labels?
asking because also in yaml mode, auto-entities chokes on using label as filter, breaking the frontend to a halt

if you want to use labels, create a template filter using filter, the works fine. At least in yaml mode.

**Comment by Calzor-Suzay** [comment]
It happens with anything, you basically "Select property" from the drop down, you get the full list and no matter what you pick it does nothing. I'm assuming you pick something then the value field appears but it never does and the select property reverts to blank.

**Comment by Mariusthvdb** [comment]
in that case ignore my post above. 

and yes I can confirm the UI to be borked, I don't even get past this creating a new card:

<img width="1047" alt="Scherm­afbeelding 2025-01-08 om 14 31 15" src="https://github.com/user-attachments/assets/10885176-d65f-43ec-af98-520a4df02496" />

**Comment by der-seemann** [comment]
same here I guess...

`Logger: frontend.js.modern.202501090
Quelle: components/system_log/__init__.py:331
Erstmals aufgetreten: 14:14:34 (2 Vorkommnisse)
Zuletzt protokolliert: 14:14:44

Uncaught error from Firefox 134.0 on Ubuntu TypeError: "filter" is read-only _changeFilter (/hacsfiles/lovelace-auto-entities/auto-entities.js:1:33021) _renderFilterEditor/</< (/hacsfiles/lovelace-auto-entities/auto-entities.js:69:46) handleEvent (/hacsfiles/lovelace-auto-entities/auto-entities.js:1:14430) dispatchEvent (src/common/dom/fire_event.ts:75:7) addValueChangedListener (src/components/ha-form/ha-form.ts:210:16) dispatchEvent (src/common/dom/fire_event.ts:75:7) ev.stopPropagation (src/components/ha-form/ha-form-select.ts:68:14) call (src/lit-html.ts:2018:28) dispatchEvent (src/common/dom/fire_event.ts:75:7) fireEvent (src/components/ha-selector/ha-selector-select.ts:293:14)`

**Comment by der-seemann** [comment]
same here I guess...
Error log:

Logger: frontend.js.modern.202501090
Quelle: components/system_log/__init__.py:331
Erstmals aufgetreten: 14:14:34 (2 Vorkommnisse)
Zuletzt protokolliert: 14:14:44

Uncaught error from Firefox 134.0 on Ubuntu TypeError: "filter" is read-only _changeFilter (/hacsfiles/lovelace-auto-entities/auto-entities.js:1:33021) _renderFilterEditor/</< (/hacsfiles/lovelace-auto-entities/auto-entities.js:69:46) handleEvent (/hacsfiles/lovelace-auto-entities/auto-entities.js:1:14430) dispatchEvent (src/common/dom/fire_event.ts:75:7) addValueChangedListener (src/components/ha-form/ha-form.ts:210:16) dispatchEvent (src/common/dom/fire_event.ts:75:7) ev.stopPropagation (src/components/ha-form/ha-form-select.ts:68:14) call (src/lit-html.ts:2018:28) dispatchEvent (src/common/dom/fire_event.ts:75:7) fireEvent (src/components/ha-selector/ha-selector-select.ts:293:14)

**Comment by iamandymcinnes** [comment]
The issue is with it trying to load the entities constantly, it automatically tries to render them and I think as you start with everything, it just borks everything as it crashes. When you select a filter property it wipes it out as it starts trying to refresh the entity list. My suggestion would be stop refreshing the entity list all the time when using the editor, either wait for a save or have a manual refresh button so you can update the preview when you are ready.

**Comment by brandon-fryslie** [comment]
If you look at the browser console the error is pretty clear.  the javascript code is trying to assign a value to a variable that is read-only.  I'm guess there was another change somewhere else, or a change in the browsers behavior, that is causing this property to become read-only.  Here is the stack trace:

```javascript
Uncaught TypeError: Cannot assign to read only property 'filter' of object '#<Object>'
    at Lt._changeFilter (auto-entities.js?hacstag=1677445841130:1:33013)
    at Lt.<anonymous> (auto-entities.js?hacstag=1677445841130:69:46)
    at K.handleEvent (auto-entities.js?hacstag=1677445841130:1:14430)
    at r (fire_event.ts:75:8)
    at ShadowRoot.<anonymous> (ha-form.ts:210:7)
    at r (fire_event.ts:75:8)
    at F.value (ha-form-select.ts:68:5)
    at z.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:75:8)
    at F.value (ha-selector-select.ts:293:5)
```
